server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOSTNAME}:8091/eureka/
  instance:
    preferIpAddress: true
  instance:
    ipAddress: ${HOSTNAME}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-customer
          uri: lb://service-customer
          predicates:
            - Path=/customers/**
        - id: service-photo
          uri: lb://service-photo
          predicates:
            - Path=/photos/**
  
            